export default {
  uy: 'Home',
  biz_haqimizda: 'About',
  portfolio: 'Contact',
  dukon: 'Shop',
  aloqa: 'Contact',
  dModel: '3D models',
  tayyorLoyiha: 'Finished projects',
  konstruksiya: 'Construction',
  kuproq: 'More',
  platforma: 'Our platform',
  loyiha: 'Our project',
  bizning_dukon: 'Our shop',
  set: 'Social networks',
  footer_title:
    '40A Taraqqiyot street, Termiz city, Surkhandarya region, Republic of Uzbekistan',
  home_title: 'The prosperity of our city with our buildings',
  yangi: 'New',
  top: 'Top',
  noResult: 'Not found',
  qidirish: 'Search',
  loyiha_nomi:
    "The company's architectural services include an in-depth study of the object, conceptual solution and preparation of working drawings. We take into account all requirements for buildings and offer the best solutions for the implementation of tasks.",
  maydon: 'Square',
  xona: 'Room',
  etaj: 'Floor',
  narx: 'Price',
  loyiha_kurish: 'View',
  loyihaga_utish: 'Go to project',
  platform_title:
    "The company's architectural services include an in-depth study of the object, conceptual solution and preparation of working drawings. We take into account all requirements for buildings and offer the best solutions for the implementation of tasks.",
  modellashtirish: '3D modeling',
  render: 'Render :',
  razmer: 'Size :',
  slinyak: 'Slug :',
  vaqt: 'Date :',
  loyihalar: 'Projects',
  xonaNomi: 'Room name',
  manzil: 'Address',
  faylTuri: 'File type',
  sertifikat: 'Our Certificates',
  sertiTitle:
    "The company's architectural services include a thorough study of the object, preparation of a conceptual solution and working drawings. We take into account all the requirements for buildings and offer the best solutions for the implementation of the tasks.",
  kompHaqida: 'About our company',
  buyProduct: 'purchase',
  telNumber: 'Phone number',
  purchase: 'Buy',
  download: 'Download',
  downloadThis: "A download link will appear here"
}
