export default {
  uy: 'Uy',
  biz_haqimizda: 'Biz haqimizda',
  portfolio: 'Aloqa',
  dukon: "Do'kon",
  aloqa: 'Aloqa',
  dModel: '3D Model',
  tayyorLoyiha: 'Tayyor loyiha',
  konstruksiya: 'Konstruksiya',
  kuproq: 'Batafsil',
  platforma: 'Bizning platforma',
  loyiha: 'Bizning loyiha',
  bizning_dukon: "Bizning do'kon",
  set: 'Ijtimoiy tarmoqlar',
  footer_title:
    "O'zbekiston Respublikasi Surxondaryo viloyati Termiz shahri Taraqqiyot ko'chasi 40A-uy",
  home_title: 'Binolarimiz bilan shahrimiz obodligi',
  yangi: 'Yangi',
  top: 'Top',
  noResult: "Ma'lumot yo'q",
  qidirish: 'Qidirish',
  loyiha_nomi:
    "Kompaniyaning arxitektura xizmatlari ob'ektni chuqur o'rganish, kontseptual yechim va ishchi chizmalarni tayyorlashni o'z ichiga oladi. Biz binolar uchun barcha talablarni hisobga olamiz va vazifalarni amalga oshirish uchun eng yaxshi echimlarni taklif qilamiz.",
  maydon: 'Maydon',
  xona: 'Xona',
  etaj: 'Etaj',
  narx: 'Narx',
  loyiha_kurish: "Ko'rish",
  loyihaga_utish: "Loyihaga o'tish",
  platform_title:
    "Kompaniyaning arxitektura xizmatlari ob'ektni chuqur o'rganish, kontseptual yechim va ishchi chizmalarni tayyorlashni o'z ichiga oladi. Biz binolar uchun barcha talablarni hisobga olamiz va vazifalarni amalga oshirish uchun eng yaxshi echimlarni taklif qilamiz.",
  modellashtirish: '3D modellashtirish',
  render: 'Render :',
  razmer: "O'lcham :",
  slinyak: 'Slug :',
  vaqt: 'Sana :',
  loyihalar: 'Loyihalar',
  xonaNomi: 'Xona nomi',
  manzil: 'Manzil',
  faylTuri: 'Fayl turi',
  sertifikat: 'Bizning sertifikatlarimiz',
  sertiTitle:
    "Kompaniyaning arxitektura xizmatlari ob'ektni chuqur o'rganish, kontseptual yechim va ishchi chizmalarni tayyorlashni o'z ichiga oladi. Biz binolar uchun barcha talablarni hisobga olamiz va vazifalarni amalga oshirish uchun eng yaxshi echimlarni taklif qilamiz.",
  kompHaqida: 'Kompaniyamiz haqida',
  buyProduct: 'Sotib olish',
  telNumber: 'Telefon raqam',
  purchase: 'Sotib olmoq',
  download: 'Yuklab olish',
  downloadThis: "Yuklab olish link paydo bo'ladi bu yerda",
}
